# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 50ee20da386232fb9a14ebe98935138e3ce65fa72689050883959ef8954d7ea0d40b966da234c4f691cf2d52e90fdac3589ae2b839aac4b35bd7daef5a249902

test:
  secret_key_base: 11a9b502d67343ff6dbb0ee598923b69dbc2066c2ae164462c2169238cae47278ff9d9bfe096c6cca7a0ee05ca74744aed59f6e197819ee2fa91df268c879e3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
